apiVersion: v1
kind: Service
metadata:
  name: {{ template "vernemq.fullname" . }}
  labels:
    app: {{ template "vernemq.name" . }}
    chart: {{ template "vernemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app: {{ template "vernemq.name" . }}
    release: {{ .Release.Name }}